version: "3"
services:
    app:
        container_name: autogluon
        build:
            context: ./../../.
            dockerfile: ./src/autogluon/Dockerfile.compose
        command: python /app/src/autogluon/run_autogluon.py
        volumes:
            - ".:/app/src/autogluon"
