version: "3"
services:
    app:
        container_name: autogluon
        build:
            context: ./../../.
            dockerfile: ./src/autogluon/Dockerfile.autogluon
        command: python /app/src/autogluon/run_autogluon.py
        volumes:
            - "./out:/app/src/autogluon/out"
