FROM python:3.8

WORKDIR /app

COPY ./data /app/data
COPY ./src/autogluon /app/src/autogluon 

# Upgrading pip and installing packages 
RUN pip install --upgrade pip setuptools wheel
RUN python -m pip install -U "mxnet<2.0.0"
RUN python -m pip install autogluon seaborn sklearn pandas